apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - mysql-configmap.yml
    - mysql-storage.yml
    - mysql-deploy.yml
    - mysql-service.yml

namespace: mysql

commonLabels:
    env: dev
